# Generated by Django 3.2.9 on 2022-01-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyforjob1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('ifile', models.FileField(blank=True, upload_to='doc')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.candidate')),
                ('jobno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.postjob')),
            ],
        ),
    ]
