# Generated by Django 3.2.9 on 2022-01-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220104_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjobs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.candidate'),
        ),
        migrations.CreateModel(
            name='appliedjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.postjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.candidate')),
            ],
        ),
    ]
