# Generated by Django 3.2.9 on 2022-01-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220104_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob1',
            name='image',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
    ]
