# Generated by Django 3.2.9 on 2022-01-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_applyforjob1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='jobno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.postjob'),
        ),
    ]
